apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cnj-resilience-backend-javaee.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cnj-resilience-backend-javaee.name" . }}
    helm.sh/chart: {{ include "cnj-resilience-backend-javaee.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cnj-resilience-backend-javaee.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
      - protocol: TCP
        port: 8080